### ISSUE TITLE
Change path parameters to query string parameters

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#26]
### Issue description
Based on lessons learned from the sitewide-search and bestbets APIs and others, we should change the Autosuggest and Drugs controllers to retrieve their search inputs as query parameters instead of path segments.  (Path segments are cool, but they run into problems with search items such as `/`, `bin`, '2/3` and so forth.)

> **ESTIMATE** 20

### What's the expected change?
- AutosuggestController::GetSuggestions - Make `searchText` a query string parameter.
- ~DrugsController::Expand - Make `character` a query string parameter.~
- ~DrugsController::GetById - Make `id` a query string parameter.~
- ~DrugsController::GetByName - Make `prettyUrlName` a query string parameter.~
- DrugsController::Search - Make `query` a query string parameter.

In addition to the controllers, the integration tests will need to be updated to move the parameter from the path to the params list.

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bryanpizzillo** [comment]
These two items should not be modified as their paths are already URL safe (e.g. /drugs/12334 or /drugs/my-drug)
* DrugsController::GetById - Make id a query string parameter.
* DrugsController::GetByName - Make prettyUrlName a query string parameter.

**Comment by blairlearn** [comment]
Per team discussion, `Expand`, `GetById` and `GetByName` will continue to get parameters via the path.  Only Autosuggest and Search will be updated to query string params.
