### ISSUE TITLE
Searching for '/' query is not working

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/drug-dictionary-api#27]
### Issue description
The API is not returning correct results when searching with a query containing /

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  on cancer gov Drug Dictionary search for **/cd40** with _contains_
2. There are two results returned that contain /CD40
3. Execute `/Drugs/search/{query}` with '/cd40' matchType 'Contains' in Swagger
4. There are 23 results returned that are matched against just CD40 (without appended /)

### What's the expected result?
- it should only return the term that contains **/cd40**

### What's the actual result?
- returns terms containing **cd40**

### Additional details / screenshot
<img width="651" alt="Screen Shot 2020-08-19 at 1 50 34 PM" src="https://user-images.githubusercontent.com/56886837/90671645-fecf8600-e222-11ea-89fb-37bf8b19e340.png">

<img width="858" alt="Screen Shot 2020-08-19 at 1 51 04 PM" src="https://user-images.githubusercontent.com/56886837/90671672-07c05780-e223-11ea-9678-ea0764fecf14.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This is likely related to NCIOCPL/bestbets-api#34.

It will likely be corrected by #26

**Comment by KateMashkinaNIH** [comment]
Tested PR #30  - this issue is resolved by it

**Comment by blairlearn** [comment]
Resolved by #30.  Closing manually.
