### ISSUE TITLE
Create the API Solution

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#3]
This should mostly be a matter of copying code from the [glossary-api](https://github.com/NCIOCPL/glossary-api/) project

- [ ] Rename `glossary-api.sln` to `drug-dictionary-api.sln`
- [ ] Rename the `NCIOCPL.Api.Glossary` project to `NCIOCPL.Api.DrugDictionary`
- [ ] Rename the `NCIOCPL.Api.GlossaryTests.` project to `NCIOCPL.Api.DrugDictionaryTests`
- [ ] Rename the project files.
- [ ] Update the entries in `drug-dictionary-api.sln`
- [ ] Comment out the contents of the controller and, service classes and the service interfaces.

**Comment by blairl-nih** [comment]
Implemented in 58ff0977be2de9e68dd1fab266abae335b23bb76
