### ISSUE TITLE
Definitions should not contain links

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#34]
The definition elements of DrugTerms contain links to search for active clinical trials  using the drug and also to the drug's entry in the NCI Thesaurus.  Assembling links should be left to the application.

```
 ...  <a ref=\"https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/C1853\">active clinical trials</a> using this agent. (<a ref=\"https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1853\">NCI Thesaurus</a>)"
```

Additionally, the non-HTML copy of the definition contains the undecorated text
> Check for active clinical trials using this agent. (NCI Thesaurus)

**ESTIMATE** 20

### Steps to reproduce the issue

1.  Browse to https://webapis-dev.cancer.gov/drugdictionary/v1/Drugs/37792

### What's the expected result?
- The HTML definition should contain links to neither the clinical trial search nor the EVS.
- The text definition should not end with the text "Check for active clinical trials using this agent. (NCI Thesaurus)"

### What's the actual result?
- The HTML definition contains links to the clinical trial search and the EVS.
- The text definition ends with the text "Check for active clinical trials using this agent. (NCI Thesaurus)"

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* JIRA issue: OCECDR-4892

**Comment by bkline** [comment]
This has been implemented and installed on CDR DEV, and pushed to ncias-d2433-v (ElasticSearch dev) and the dictionary tables in the `pdq_dictionaries` tables on ncidb-d202-v.

**Comment by bkline** [comment]
Let me know if the results what you need, @blairlearn.

**Comment by blairlearn** [comment]
The definitions look right to me.

I do need another data dump however so I can update the integration tests.

**Comment by bkline** [comment]
GitHub doesn't like json, so I put it in the Slack thread. 🤨

**Comment by blairlearn** [comment]
Fixed.
