### ISSUE TITLE
Modify loader to properly handle terms starting with letters which have diacritics.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#37]
NCIOCPL/glossary-api#137 demonstrates a problem with diacritics not being treated as letters.  This same flaw likely applies to the drug loader as well.

> **ESTIMATE** 20

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bkline** [comment]
Modified requirement implemented on DEV. Fresh test set attached.

[drugs.zip](https://github.com/NCIOCPL/drug-dictionary-api/files/5283003/drugs.zip)

**Comment by blairlearn** [comment]
All that, and it turns out there no drug names (or aliases) which use diacritics and might be used to test this.

We shall for now assume that it works.
