### ISSUE TITLE
Increase max_gram value to 100 for ngram_analyzer

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/drug-dictionary-api#45]
### Issue description
Related to NCIOCPL/drug-dictionary-app#70, we need to adjust the `ngram_analyzer` to allow contains searches of up to 100 characters.  Currently, any search with more 30 characters fails due to being too long.

The drug dictionary application will in turn be modified to only search for a maximum of 100 characters.

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by zhuomingao** [comment]
{
  "settings": {
    "index": {
      "number_of_shards": "1",
      "analysis": {
        "filter": {
          "autocomplete_filter": {
            "type": "edge_ngram",
            "min_gram": 1,
            "max_gram": 30,
            "token_chars": [
              "letter",
              "digit",
              "punctuation",
              "symbol"
            ]
          },
          "ngram_filter": {
            "type": "ngram",
            "min_gram": 1,
            "max_gram": 100,
            "token_chars": [
              "letter",
              "digit",
              "punctuation",
              "symbol"
            ]
          }
        },
        "analyzer": {
          "autocomplete_index": {
            "type": "custom",
            "tokenizer": "classic",
            "filter": [
              "lowercase",
              "autocomplete_filter",
              "asciifolding"
            ]
          },
          "lowercase_search": {
            "filter": [
              "lowercase",
              "asciifolding"
            ],
            "tokenizer": "keyword"
          },
          "ngram_analyzer": {
            "type": "custom",
            "tokenizer": "keyword",
            "filter": [
              "lowercase",
              "ngram_filter",
              "asciifolding"
            ]
          },
          "autocomplete_search": {
            "type": "custom",
            "tokenizer": "classic",
            "filter": [
              "lowercase",
              "asciifolding"
            ]
          }
        },
        "normalizer": {
          "caseinsensitive_normalizer": {
            "type": "custom",
            "char_filter": [],
            "filter": [
              "lowercase",
              "asciifolding"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "terms": {
      "dynamic": "strict",
      "properties": {
        "name": {
          "type": "keyword",
          "normalizer": "caseinsensitive_normalizer",
          "fields": {
            "_autocomplete": {
              "type": "text",
              "analyzer": "autocomplete_index",
              "search_analyzer": "autocomplete_search"
            },
            "_contain": {
              "type": "text",
              "analyzer": "ngram_analyzer",
              "search_analyzer": "lowercase_search"
            }
          }
        },
        "type": {
          "type": "keyword"
        },
        "term_name_type": {
          "type": "keyword"
        },
        "first_letter": {
          "type": "keyword",
          "normalizer": "caseinsensitive_normalizer"
        },
        "preferred_name": {
          "type": "keyword",
          "normalizer": "caseinsensitive_normalizer"
        },
        "aliases": {
          "type": "nested",
          "include_in_root": true,
          "properties": {
            "type": {
              "type": "keyword"
            },
            "name": {
              "type": "keyword",
              "normalizer": "caseinsensitive_normalizer",
              "fields": {
                "_contain": {
                  "type": "text",
                  "analyzer": "ngram_analyzer",
                  "search_analyzer": "lowercase_search"
                }
              }
            }
          }
        },
        "definition": {
          "properties": {
            "html": {
              "type": "keyword"
            },
            "text": {
              "type": "keyword"
            }
          }
        },
        "term_id": {
          "type": "long"
        },
        "pretty_url_name": {
          "type": "keyword"
        },
        "nci_concept_id": {
          "type": "keyword"
        },
        "nci_concept_name": {
          "type": "keyword"
        },
        "drug_info_summary_link": {
          "properties": {
            "text": {
              "type": "keyword"
            },
            "url": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

**Comment by blairlearn** [comment]
**Update:**  Pending client approval, rather than try to work around this in the API, we'll change the application to do searches for only the first 30 characters and disallow autosuggest for more than 30 characters.

See Drug Dictionary Application change request tickets [89](https://github.com/NCIOCPL/drug-dictionary-app/issues/89) and [90](https://github.com/NCIOCPL/drug-dictionary-app/issues/90)
