### ISSUE TITLE
Limit autosuggest to 30 characters

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/drug-dictionary-api#48]
### Issue description
We'd like to limit the API to only return autosuggest results that match contains searches when the items are 30 characters or less.  Items 31 characters and above will not be returned by the API.

> **ESTIMATE** TBD

### What's the expected change?
We'd like to limit the API to only return autosuggest results that match contains searches when the items are 30 characters or less.  Items 31 characters and above will not be returned by the API.

### What's the current functionality?
API returns all results

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by blairlearn** [comment]
Completed in f3d3631debac3fd4c2589fab719e8d0ccd1dabe8
